version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    groups:
      dotnet-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # NPM dependencies for frontend
  - package-ecosystem: "npm"
    directory: "/src/TodoApp.Web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-production:
        dependency-type: "production"
        update-types:
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/src/TodoApp.Api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"

  - package-ecosystem: "docker"
    directory: "/src/TodoApp.Web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5