# Add 'size/XS' label to PRs with less than 10 changes
size/XS:
  - changed-files:
    - count: '<10'

# Add 'size/S' label to PRs with 10-50 changes
size/S:
  - changed-files:
    - count: '>=10'
    - count: '<50'

# Add 'size/M' label to PRs with 50-200 changes
size/M:
  - changed-files:
    - count: '>=50'
    - count: '<200'

# Add 'size/L' label to PRs with 200-500 changes
size/L:
  - changed-files:
    - count: '>=200'
    - count: '<500'

# Add 'size/XL' label to PRs with 500+ changes
size/XL:
  - changed-files:
    - count: '>=500'

# Add labels based on file paths
backend:
  - changed-files:
    - any-glob-to-any-file: 'src/TodoApp.Api/**'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/TodoApp.Web/**'

tests:
  - changed-files:
    - any-glob-to-any-file: '**/*.Tests/**'
    - any-glob-to-any-file: '**/*.test.ts'
    - any-glob-to-any-file: '**/*.test.tsx'

documentation:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: '**/*.md'

infrastructure:
  - changed-files:
    - any-glob-to-any-file: 'docker-compose*.yml'
    - any-glob-to-any-file: '**/Dockerfile*'
    - any-glob-to-any-file: '.github/**'