version: '3.8'

services:
  postgres:
    ports:
      - "5433:5432"
  
  maildev:
    image: maildev/maildev
    container_name: todoapp-maildev
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080