services:
  # Database
  postgres:
    image: postgres:16-alpine
    container_name: todoapp-postgres
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp_password
      POSTGRES_DB: todoapp_db
    volumes:
      - todoapp_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todoapp" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todoapp-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: src/TodoApp.Api/Dockerfile
    container_name: todoapp-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Database=todoapp_db;Username=todoapp;Password=todoapp_password
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todoapp-network
    profiles:
      - production

  # Frontend
  web:
    build:
      context: .
      dockerfile: src/TodoApp.Web/Dockerfile
    container_name: todoapp-web
    depends_on:
      - api
    ports:
      - "8080:80"
    networks:
      - todoapp-network
    profiles:
      - production

  # Development API with hot reload
  api-dev:
    build:
      context: .
      dockerfile: src/TodoApp.Api/Dockerfile.dev
    container_name: todoapp-api-dev
    volumes:
      - ./src/TodoApp.Api:/app
      - todoapp_nuget_cache:/root/.nuget/packages
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Database=todoapp_db;Username=todoapp;Password=todoapp_password
      ASPNETCORE_URLS: http://0.0.0.0:5050
    ports:
      - "5050:5050"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - todoapp-network
    profiles:
      - development

  # Development Frontend with hot reload
  web-dev:
    build:
      context: ./src/TodoApp.Web
      dockerfile: Dockerfile.dev
    container_name: todoapp-web-dev
    volumes:
      - ./src/TodoApp.Web:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:5050/api/v1
    ports:
      - "5180:5173"
    networks:
      - todoapp-network
    profiles:
      - development

volumes:
  todoapp_postgres_data:
  todoapp_nuget_cache:


networks:
  todoapp-network:
    driver: bridge
