version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: todoapp-postgres
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp_password
      POSTGRES_DB: todoapp_db
    volumes:
      - todoapp_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  todoapp_postgres_data: